name = "ruteclien"
compatibility_date = "2024-03-20"
main = "src/worker.ts"

[assets]
directory = "dist"
binding = "ASSETS"

[[kv_namespaces]]
binding = "accounts_kv"
id = "fc7e78f9ecec4a4b95fbf4ab82e1e057"
